// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "github.com/egorka-gh/zbazar/zsync/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeListVersionHandler(m, endpoints, options["ListVersion"])
	makePullPackHandler(m, endpoints, options["PullPack"])
	makePushPackHandler(m, endpoints, options["PushPack"])
	makePackDoneHandler(m, endpoints, options["PackDone"])
	makeAddActivityHandler(m, endpoints, options["AddActivity"])
	makeGetLevelHandler(m, endpoints, options["GetLevel"])
	
	return m
}
