// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "github.com/egorka-gh/zbazar/zsync/pkg/endpoint"
	http1 "github.com/egorka-gh/zbazar/zsync/pkg/http"
	service "github.com/egorka-gh/zbazar/zsync/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"AddActivity": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "AddActivity", logger))},
		"GetLevel":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetLevel", logger))},
		"ListVersion": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ListVersion", logger))},
		"PackDone":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PackDone", logger))},
		"PullPack":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PullPack", logger))},
		"PushPack":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PushPack", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["ListVersion"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ListVersion")), endpoint.InstrumentingMiddleware(duration.With("method", "ListVersion"))}
	mw["PullPack"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PullPack")), endpoint.InstrumentingMiddleware(duration.With("method", "PullPack"))}
	mw["PushPack"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PushPack")), endpoint.InstrumentingMiddleware(duration.With("method", "PushPack"))}
	mw["PackDone"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PackDone")), endpoint.InstrumentingMiddleware(duration.With("method", "PackDone"))}
	mw["AddActivity"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "AddActivity")), endpoint.InstrumentingMiddleware(duration.With("method", "AddActivity"))}
	mw["GetLevel"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetLevel")), endpoint.InstrumentingMiddleware(duration.With("method", "GetLevel"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"ListVersion", "PullPack", "PushPack", "PackDone", "AddActivity", "GetLevel"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
